spring:
  thymeleaf:
    cache: false
  devtools:
    remote:
      restart:
        enabled: true
    livereload:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/project
    username: postgres
    password: postgres
  jpa:
    database: postgresql
    generate-ddl: false
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
#mybatis:
#  config-location: classpath:mapper/**/*.xml
#  configuration:
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.example.core.model
#    map-underscore-to-camel-case: true

jwt:
  secret: YXNkZndlZmFzZGZhc2R2a25hd2V2aXVhc25sa3Zram5sYWR2