spring.thymeleaf.cache=false
spring.devtools.remote.restart.enabled=true
spring.devtools.livereload.enabled=true
#spring.devtools.livereload.port=8080
spring.web.resources.static-locations=classpath: /static/